import os
import requests

def news_list_by_region(region_id):
    """
    :API_description: Retrieve the latest financial news and market data, including currency exchange rates, commodity prices, and equity indices, grouped by region.
    :param region_id: The ID of the region for which to retrieve news articles.
    One of the following is allowed: home-v3|asia-home-v3|europe-home-v3|middle-east-home-v3|africa-home-v3|canada-home-v3
    :response_schema: 
    ```json
    {
      "title": "string or null",
      "id": "string",
      "indexBar": {
        "enabled": "boolean",
        "quotes": [
          {
            "EURUSD:CUR": {
              "baseName": "string",
              "securityType": "string",
              "symbol": "string",
              "country": "string",
              "currency": "string",
              "resourceType": "string",
              "resourceSubtype": "string",
              "region": "string",
              "ticker": "string",
              "tickerName": "string",
              "template": "string",
              "tinyName": "string",
              "name": "string",
              "watchlist": "boolean",
              "resourceId": "string",
              "last": "string",
              "netChange": "string",
              "lastPriceTime": "integer",
              "yearHigh": "string",
              "dayHigh": "string",
              "yearLow": "string",
              "sourceCurrency": "string",
              "dayLow": "string",
              "pctChange": "string",
              "sparkline": {
                "href": "string"
              }
            }
          },
          {
            "CL1:COM": {
              "securityType": "string",
              "symbol": "string",
              "country": "string",
              "currency": "string",
              "resourceType": "string",
              "resourceSubtype": "string",
              "region": "string",
              "ticker": "string",
              "tickerName": "string",
              "template": "string",
              "tinyName": "string",
              "name": "string",
              "watchlist": "boolean",
              "resourceId": "string",
              "last": "string",
              "netChange": "string",
              "lastPriceTime": "integer",
              "unit": "string",
              "dayHigh": "string",
              "dayLow": "string",
              "pctChange": "string",
              "sparkline": {
                "href": "string"
              }
            }
          },
          {
            "INDU:IND": {
              "securityType": "string",
              "symbol": "string",
              "country": "string",
              "currency": "string",
              "resourceType": "string",
              "fundamentalDataCurrency": "string",
              "resourceSubtype": "string",
              "region": "string",
              "ticker": "string",
              "tickerName": "string",
              "template": "string",
              "tinyName": "string",
              "name": "string",
              "watchlist": "boolean",
              "resourceId": "string",
              "eqtIndex": "boolean",
              "last": "string",
              "netChange": "string",
              "lastPriceTime": "integer",
              "pctChange1M": "string",
              "yearHigh": "string",
              "dayHigh": "string",
              "volume": "integer",
              "yearLow": "string",
              "dayLow": "string",
              "pctChangeYTD": "string",
              "pctChange": "string",
              "isOpen": "boolean",
              "sparkline": {
                "href": "string"
              }
            }
          }
        ],
        "stories": [
          {
            "id": "string",
            "type": "string",
            "internalID": "string",
            "title": "string",
            "summary": "string",
            "autoGeneratedSummary": "string",
            "abstract": ["string"],
            "published": "integer",
            "updatedAt": "integer",
            "wordCount": "integer",
            "premium": "boolean",
            "secondaryBrands": ["string"],
            "byline": "string",
            "shortURL": "string",
            "longURL": "string",
            "primaryCategory": "string",
            "primarySite": "string",
            "eyebrowSite": "string",
            "readings": [
              {
                "url": "string",
                "voice": "string",
                "durationMs": "integer"
              }
            ],
            "image": "string",
            "thumbnailImage": "string",
            "aspectRatio": "number",
            "card": "string",
            "contentTags": [
              {
                "id": "string",
                "type": "string"
              }
            ],
            "isMetered": "boolean",
            "meta": {
              "newsletterToutLabel": "string or null",
              "newsletterSlug": "string or null",
              "terminalBlogId": "string or null"
            },
            "related": []
          }
        ]
      },
      "modules": [
        {
          "id": "string",
          "title": "string or null",
          "skipDedup": "boolean",
          "mobileSkipPageDedupe": "boolean",
          "type": "string",
          "appPresentationStyle": "string",
          "mobileMaximum": "string",
          "tracking": {
            "id": "string",
            "title": "string"
          },
          "stories": []
        },
        {
          "id": "string",
          "title": "string or null",
          "skipDedup": "boolean",
          "mobileSkipPageDedupe": "boolean",
          "type": "string",
          "appPresentationStyle": "string",
          "mobileMaximum": "string",
          "tracking": {
            "id": "string",
            "title": "string"
          },
          "stories": [
            {
              "id": "string",
              "type": "string",
              "internalID": "string",
              "title": "string",
              "summary": "string",
              "autoGeneratedSummary": "string",
              "abstract": [],
              "published": "integer",
              "updatedAt": "integer",
              "wordCount": "integer",
              "premium": "boolean",
              "franchise": "string",
              "secondaryBrands": ["string"],
              "byline": "string",
              "shortURL": "string",
              "longURL": "string",
              "primaryCategory": "string",
              "primarySite": "string",
              "eyebrowSite": "string",
              "labelDropdown": {
                "labelText": "string",
                "labelStyle": {
                  "fontSize": "integer",
                  "letterSpacing": "integer",
                  "darkTheme": {
                    "textColor": "string"
                  },
                  "lightTheme": {
                    "textColor": "string"
                  },
                  "fontWeight": "integer"
                }
              },
              "readings": [],
              "image": "string",
              "thumbnailImage": "string",
              "aspectRatio": "number",
              "card": "string",
              "contentTags": [],
              "isMetered": "boolean",
              "meta": {
                "newsletterToutLabel": "string or null",
                "newsletterSlug": "string or null",
                "terminalBlogId": "string"
              },
              "related": []
            },
            {
              "id": "string",
              "type": "string",
              "internalID": "string",
              "title": "string",
              "summary": "string",
              "autoGeneratedSummary": "string",
              "abstract": ["string"],
              "published": "integer",
              "updatedAt": "integer",
              "wordCount": "integer",
              "premium": "boolean",
              "franchise": "string",
              "secondaryBrands": ["string"],
              "byline": "string",
              "shortURL": "string",
              "longURL": "string",
              "primaryCategory": "string",
              "primarySite": "string",
              "eyebrowSite": "string",
              "readings": [],
              "image": "string",
              "thumbnailImage": "string",
              "aspectRatio": "number",
              "card": "string",
              "contentTags": [
                {
                  "id": "string",
                  "type": "string"
                }
              ],
              "isMetered": "boolean",
              "meta": {
                "newsletterToutLabel": "string or null",
                "newsletterSlug": "string or null",
                "terminalBlogId": "string or null"
              },
              "related": []
            }
          ]
        },
        {
          "id": "string",
          "title": "string or null",
          "skipDedup": "boolean",
          "mobileSkipPageDedupe": "boolean",
          "type": "string",
          "mobileMaximum": "string",
          "tracking": {
            "id": "string",
            "title": "string"
          },
          "stories": [
            {
              "id": "string",
              "type": "string",
              "internalID": "string",
              "title": "string",
              "summary": "string",
              "autoGeneratedSummary": "string",
              "abstract": ["string"],
              "published": "integer",
              "updatedAt": "integer",
              "wordCount": "integer",
              "premium": "boolean",
              "label": "string",
              "secondaryBrands": ["string"],
              "byline": "string",
              "shortURL": "string",
              "longURL": "string",
              "primaryCategory": "string or null",
              "primarySite": "string",
              "eyebrowSite": "string",
              "readings": [
                {
                  "url": "string",
                  "voice": "string",
                  "durationMs": "integer"
                }
              ],
              "image": "string",
              "thumbnailImage": "string",
              "aspectRatio": "number",
              "card": "string",
              "contentTags": [
                {
                  "id": "string",
                  "type": "string"
                }
              ],
              "isMetered": "boolean",
              "meta": {
                "newsletterToutLabel": "string or null",
                "newsletterSlug": "string or null",
                "terminalBlogId": "string or null"
              },
              "related": []
            },
            {
              "id": "string",
              "type": "string",
              "internalID": "string",
              "title": "string",
              "summary": "string",
              "autoGeneratedSummary": "string",
              "abstract": ["string"],
              "published": "integer",
              "updatedAt": "integer",
              "wordCount": "integer",
              "premium": "boolean",
              "label": "string",
              "secondaryBrands": ["string"],
              "byline": "string",
              "shortURL": "string",
              "longURL": "string",
              "primaryCategory": "string or null",
              "primarySite": "string",
              "eyebrowSite": "string",
              "readings": [
                {
                  "url": "string",
                  "voice": "string",
                  "durationMs": "integer"
                }
              ],
              "image": "string",
              "thumbnailImage": "string",
              "aspectRatio": "number",
              "card": "string",
              "contentTags": [
                {
                  "id": "string",
                  "type": "string"
                }
              ],
              "isMetered": "boolean",
              "meta": {
                "newsletterToutLabel": "string or null",
                "newsletterSlug": "string or null",
                "terminalBlogId": "string or null"
              },
              "related": []
            }
          ]
        }
      ]
    }
    ```
    """
    url = "https://bb-finance.p.rapidapi.com/news/list-by-region"
    rapid_api_key = os.getenv('RAPID_API_KEY')
    querystring = {"id": region_id}

    headers = {
        "x-rapidapi-key": rapid_api_key,
        "x-rapidapi-host": "bb-finance.p.rapidapi.com"
    }
    response = requests.get(url, headers=headers, params=querystring)
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"API request failed with status code {response.status_code}: {response.text}")