import os
import requests

def get_market_quotes(symbols,fields):
    """
    :API_description: Retrieves comprehensive real-time and historical financial market data for specified stock symbols, including pricing, technical indicators, company fundamentals, and market statistics.
    :param symbols: Comma-separated list of stock symbols (e.g., "AAPL","AVGO","NIO","DOCU","PATH","APLD","WHLR").
    :param fields: Comma-separated list of fields to include in the response (e.g., algorithm,askSize,ask,averageDailyVolume10Day,averageDailyVolume3Month,averageForCategory,averageMaturity,averageDailyVolume3Month,beta3y,beta,bidSize,bid,bookValue,fundCategory,circulatingSupply,components,contractSymbol,currency,dividendDate,dividendRate,dividendYield,dividendsPerShare,earningsTimestampEnd,earningsTimestampStart,earningsTimestamp,ebitda,epsCurrentYear,epsForward,epsNextQuarter,epsTrailingTwelveMonths,etfcategory_scalars,exDividendDate,exchangeTimezoneName,exchangeTimezoneShortName,exchange,netExpenseRatio,expireDate,fiftyDayAverageChangePercent,fiftyDayAverageChange,fiftyDayAverage,fiftyTwoWeekHighChangePercent,fiftyTwoWeekHighChange,fiftyTwoWeekHigh,fiftyTwoWeekLowChangePercent,fiftyTwoWeekLowChange,fiftyTwoWeekLow,floatShares,forwardPE,fullExchangeName,gmtOffSetMilliseconds,headSymbolAsString).
    :response_schema: 
    ```json
{
  "quoteResponse": {
    "result": [
      {
        "language": "en-US",
        "region": "US",
        "quoteType": "EQUITY",
        "typeDisp": "Equity",
        "quoteSourceName": "Nasdaq Real Time Price",
        "triggerable": true,
        "customPriceAlertConfidence": "HIGH",
        "quoteSummary": {
          "summaryDetail": {
            "maxAge": 1,
            "priceHint": 2,
            "previousClose": 291.13,
            "open": 294.12,
            "dayLow": 291.7,
            "dayHigh": 295.93,
            "regularMarketPreviousClose": 291.13,
            "regularMarketOpen": 294.12,
            "regularMarketDayLow": 291.7,
            "regularMarketDayHigh": 295.93,
            "dividendRate": 1.08,
            "dividendYield": 0.0037,
            "exDividendDate": 1778457600,
            "payoutRatio": 0.1259,
            "fiveYearAvgDividendYield": 0.5,
            "beta": 1.086,
            "trailingPE": 35.74105,
            "forwardPE": 30.805504,
            "volume": 7335770,
            "regularMarketVolume": 7335770,
            "averageVolume": 46693596,
            "averageVolume10days": 53656670,
            "averageDailyVolume10Day": 53656670,
            "bid": 292.76,
            "ask": 297.98,
            "bidSize": 100,
            "askSize": 400,
            "marketCap": 4341266382848,
            "nonDilutedMarketCap": 4275929952280,
            "fiftyTwoWeekLow": 195.07,
            "fiftyTwoWeekHigh": 317.4,
            "allTimeHigh": 317.4,
            "allTimeLow": 0.049107,
            "priceToSalesTrailing12Months": 9.616443,
            "fiftyDayAverage": 285.4912,
            "twoHundredDayAverage": 266.86954,
            "trailingAnnualDividendRate": 1.04,
            "trailingAnnualDividendYield": 0.003572287,
            "currency": "USD",
            "fromCurrency": null,
            "toCurrency": null,
            "lastMarket": null,
            "coinMarketCapLink": null,
            "algorithm": null,
            "tradeable": false
          }
        },
        "exchange": "NMS",
        "market": "us_market",
        "fullExchangeName": "NasdaqGS",
        "marketState": "REGULAR",
        "sourceInterval": 15,
        "exchangeDataDelayedBy": 0,
        "exchangeTimezoneName": "America/New_York",
        "exchangeTimezoneShortName": "EDT",
        "gmtOffSetMilliseconds": -14400000,
        "esgPopulated": false,
        "tradeable": false,
        "cryptoTradeable": false,
        "hasPrePostMarketData": true,
        "firstTradeDateMilliseconds": 345479400000,
        "priceHint": 2,
        "regularMarketTime": 1781532287,
        "regularMarketPrice": 295.5785,
        "symbol": "AAPL"
      },
      {
        "language": "en-US",
        "region": "US",
        "quoteType": "EQUITY",
        "typeDisp": "Equity",
        "quoteSourceName": "Nasdaq Real Time Price",
        "triggerable": true,
        "customPriceAlertConfidence": "HIGH",
        "quoteSummary": {
          "summaryDetail": {
            "maxAge": 1,
            "priceHint": 2,
            "previousClose": 382.07,
            "open": 395.8,
            "dayLow": 390.25,
            "dayHigh": 396.2,
            "regularMarketPreviousClose": 382.07,
            "regularMarketOpen": 395.8,
            "regularMarketDayLow": 390.25,
            "regularMarketDayHigh": 396.2,
            "dividendRate": 2.6,
            "dividendYield": 0.0068,
            "exDividendDate": 1782086400,
            "payoutRatio": 0.41259998,
            "fiveYearAvgDividendYield": 1.87,
            "beta": 1.433,
            "trailingPE": 65.0825,
            "forwardPE": 20.18014,
            "volume": 4692274,
            "regularMarketVolume": 4692274,
            "averageVolume": 25484471,
            "averageVolume10days": 42625250,
            "averageDailyVolume10Day": 42625250,
            "bid": 394.08,
            "ask": 391.07,
            "bidSize": 100,
            "askSize": 200,
            "marketCap": 1857811251200,
            "nonDilutedMarketCap": 1817728666249,
            "fiftyTwoWeekLow": 244.17,
            "fiftyTwoWeekHigh": 495,
            "allTimeHigh": 495,
            "allTimeLow": 1.433,
            "priceToSalesTrailing12Months": 24.618185,
            "fiftyDayAverage": 406.4476,
            "twoHundredDayAverage": 358.1016,
            "trailingAnnualDividendRate": 2.54,
            "trailingAnnualDividendYield": 0.006647996,
            "currency": "USD",
            "fromCurrency": null,
            "toCurrency": null,
            "lastMarket": null,
            "coinMarketCapLink": null,
            "algorithm": null,
            "tradeable": false
          }
        },
        "exchange": "NMS",
        "market": "us_market",
        "fullExchangeName": "NasdaqGS",
        "marketState": "REGULAR",
        "sourceInterval": 15,
        "exchangeDataDelayedBy": 0,
        "exchangeTimezoneName": "America/New_York",
        "exchangeTimezoneShortName": "EDT",
        "gmtOffSetMilliseconds": -14400000,
        "esgPopulated": false,
        "tradeable": false,
        "cryptoTradeable": false,
        "hasPrePostMarketData": true,
        "firstTradeDateMilliseconds": 1249565400000,
        "priceHint": 2,
        "regularMarketTime": 1781532285,
        "regularMarketPrice": 390.495,
        "symbol": "AVGO"
      },
      {
        "language": "en-US",
        "region": "US",
        "quoteType": "EQUITY",
        "typeDisp": "Equity",
        "quoteSourceName": "Nasdaq Real Time Price",
        "triggerable": true,
        "customPriceAlertConfidence": "HIGH",
        "quoteSummary": {
          "summaryDetail": {
            "maxAge": 1,
            "priceHint": 2,
            "previousClose": 5.21,
            "open": 5.25,
            "dayLow": 5.2,
            "dayHigh": 5.29,
            "regularMarketPreviousClose": 5.21,
            "regularMarketOpen": 5.25,
            "regularMarketDayLow": 5.2,
            "regularMarketDayHigh": 5.29,
            "payoutRatio": 0,
            "beta": 0.887,
            "forwardPE": 35.53802,
            "volume": 4787941,
            "regularMarketVolume": 4787941,
            "averageVolume": 38464600,
            "averageVolume10days": 32828550,
            "averageDailyVolume10Day": 32828550,
            "bid": 5.26,
            "ask": 5.27,
            "bidSize": 1370000,
            "askSize": 1270000,
            "marketCap": 13235434496,
            "nonDilutedMarketCap": 13468096139,
            "fiftyTwoWeekLow": 3.34,
            "fiftyTwoWeekHigh": 8.02,
            "allTimeHigh": 66.99,
            "allTimeLow": 1.19,
            "priceToSalesTrailing12Months": 0.1310628,
            "fiftyDayAverage": 6.0018,
            "twoHundredDayAverage": 5.84905,
            "trailingAnnualDividendRate": 0,
            "trailingAnnualDividendYield": 0,
            "currency": "USD",
            "fromCurrency": null,
            "toCurrency": null,
            "lastMarket": null,
            "coinMarketCapLink": null,
            "algorithm": null,
            "tradeable": false
          }
        },
        "exchange": "NYQ",
        "market": "us_market",
        "fullExchangeName": "NYSE",
        "marketState": "REGULAR",
        "sourceInterval": 15,
        "exchangeDataDelayedBy": 0,
        "exchangeTimezoneName": "America/New_York",
        "exchangeTimezoneShortName": "EDT",
        "gmtOffSetMilliseconds": -14400000,
        "esgPopulated": false,
        "tradeable": false,
        "cryptoTradeable": false,
        "hasPrePostMarketData": true,
        "firstTradeDateMilliseconds": 1536759000000,
        "priceHint": 2,
        "regularMarketTime": 1781532285,
        "regularMarketPrice": 5.2822,
        "symbol": "NIO"
      }
    ],
    "error": null
  }
}
```
    """
    url = "https://yahoo-finance166.p.rapidapi.com/api/market/get-quote-v2"
    rapid_api_key = os.getenv('RAPID_API_KEY')
    querystring = { "symbols": symbols,"fields": fields}
    headers = {
        "x-rapidapi-key": rapid_api_key,
        "x-rapidapi-host": "yahoo-finance166.p.rapidapi.com"
    }
    response = requests.get(url, headers=headers, params=querystring)
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"API request failed with status code {response.status_code}: {response.text}")